"""ajout du champ fcm-token

Revision ID: ca765fe411e2
Revises: ba1f8b84265c
Create Date: 2026-08-14 19:57:42.611523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca765fe411e2'
down_revision: Union[str, Sequence[str], None] = 'ba1f8b84265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zems', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zems', 'fcm_token')
    # ### end Alembic commands ###
